In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error
from sklearn.impute import SimpleImputer
# 1. load the dataset
df = sns.load_dataset('titanic')
# check missing values in each column
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [2]:
df.columns.value_counts().sum()

np.int64(15)

In [3]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [23]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [27]:
df = sns.load_dataset('titanic')
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [33]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
df[['age']] = imputer.fit_transform(df[['age']])
# df_imputed = pd.DataFrame(df_imputed, columns=df.columns)

In [34]:
df.isnull().sum().sort_values(ascending=False)

deck           688
embarked         2
embark_town      2
age              0
survived         0
pclass           0
sex              0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [35]:
from sklearn.preprocessing import LabelEncoder
values =['sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive']
label = {}
for col in values:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label[col] = le
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,1,7,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,0,2,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,0,7,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,0,2,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,1,7,2,0,True

In [36]:
# from sklearn.preprocessing import LabelEncoder
# # Encode categorical variables
# values =['sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive']
# lb = {}
# for col in values:
#     le = LabelEncoder()
#     df[col] = le.fit_transform(df[col])
#     lb[col] = le
# df.head()

In [38]:
from sklearn.impute import IterativeImputer
imputer = IterativeImputer(max_iter=10)
values = ['age', 'fare', 'embarked', 'deck', 'embark_town', 'alive']
for col in values:
    df[[col]] = imputer.fit_transform(df[[col]])
df.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [39]:
# from sklearn.experimental import enable_iterative_imputer
# from sklearn.impute import IterativeImputer

# iterative = IterativeImputer(max_iter=10)
# columns_to_impute = ['age','embarked', 'deck', 'embark_town']
# for col in columns_to_impute:
#     df[[col]] = iterative.fit_transform(df[[col]])
# df.isnull().sum().sort_values(ascending=False)

In [7]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2.0,2,1,1,7.0,2.0,0,False
1,1,1,0,38.0,1,0,71.2833,0.0,0,2,0,2.0,0.0,1,False
2,1,3,0,26.0,0,0,7.9250,2.0,2,2,0,7.0,2.0,1,True
3,1,1,0,35.0,1,0,53.1000,2.0,0,2,0,2.0,2.0,1,False
4,0,3,1,35.0,0,0,8.0500,2.0,2,1,1,7.0,2.0,0,True

In [8]:
# df.sample(10)

In [42]:
# reverse transform the encoded values back to original categorical values
# for col in columns_to_encode:
#     df[col]= le[col].inverse_transform(df[col])

In [10]:
# df.sample(10, random_state=5)

In [11]:
# df_with_missing = df[df['sex'].isna()]
# # dropna removes all rows with missing values
# df_without_missing = df.dropna ()

In [12]:
# df.isnull().sum().sort_values(ascending=False)

In [13]:
# df.dropna(subset=['age'], inplace=True)

In [14]:
# print("The shape of the original dataset is: ", df.shape)
# print("The shape of the dataset with missing values removed is: ", df_without_missing.shape)
# print("The shape of the dataset with missing values is: ", df_with_missing.shape)

In [15]:
# df.head()

In [16]:
# df.columns

In [17]:
# df.columns.value_counts().sum()

In [46]:
df = sns.load_dataset('titanic')
# df.head()

In [47]:
df_without_missing = df.dropna ()
df_with_missing = df[df['age'].isna()]

In [54]:
print("The shape of the original dataset is: ", df.shape)
print("The shape of the dataset with missing values removed is: ", df_without_missing.shape)
print("The shape of the dataset with missing values is: ", df_with_missing.shape)

The shape of the original dataset is:  (891, 15)
The shape of the dataset with missing values removed is:  (182, 15)
The shape of the dataset with missing values is:  (177, 15)

In [49]:
df_with_missing.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True

In [63]:
x = df_without_missing.drop('age', axis=1)
y = df_without_missing['age']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
# rf_model.fit(x_train, y_train)
# y_pred = rf_model.predict(x_test)

In [66]:
cat_cols = x_train.select_dtypes(include=['object', 'category', 'bool']).columns

x_train = pd.get_dummies(x_train, columns=cat_cols, drop_first=True)
x_test = pd.get_dummies(x_test, columns=cat_cols, drop_first=True)

x_test = x_test.reindex(columns=x_train.columns, fill_value=0)

rf_model.fit(x_train, y_train)
y_pred = rf_model.predict(x_test)

In [68]:
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Absolute Percentage Error:", mean_absolute_percentage_error(y_test, y_pred))
print ("R-squared:", r2_score(y_test, y_pred))
print ("Root Mean Squared Error:", np.sqrt(mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 9.542615186615189
Mean Absolute Percentage Error: 0.8169400475388205
R-squared: 0.5545512452914501
Root Mean Squared Error: 11.813343155324596

In [72]:
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [78]:
# drop the deck column
df = df.drop('deck', axis=1)

In [80]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [79]:
df.isnull().sum().sort_values(ascending=False)

age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
parch            0
sibsp            0
class            0
fare             0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [93]:
# remove warning
import warnings
warnings.filterwarnings('ignore')
# replace the missing values with the predicted values
x_missing = df_with_missing.drop('age', axis=1)
x_missing = pd.get_dummies(x_missing, drop_first=True)
x_missing = x_missing.reindex(columns=x_train.columns, fill_value=0)

df_with_missing.loc[:, 'age'] = rf_model.predict(x_missing)
# check the missing values
df_with_missing.isnull().sum().sort_values (ascending=False)

deck           158
pclass           0
survived         0
age              0
sibsp            0
parch            0
sex              0
fare             0
embarked         0
who              0
class            0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

In [90]:
# impute embarked and embarked town with mode imputer
imputer = SimpleImputer(strategy='most_frequent')
# impute embarked and embarked town with mode imputer
imputer = SimpleImputer(strategy='most_frequent')
df['embarked'] = imputer.fit_transform(df[['embarked']]).ravel()
df['embark_town'] = imputer.fit_transform(df[['embark_town']]).ravel()

In [92]:
df.isnull().sum().sort_values(ascending=False)

age            177
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

In [98]:
# remove warning
# deck column was already removed earlier
import warnings
warnings.filterwarnings('ignore')
# replace the missing values with the predicted values
x_missing = df_with_missing.drop('age', axis=1)
x_missing = pd.get_dummies(x_missing, drop_first=True)
x_missing = x_missing.reindex(columns=x_train.columns, fill_value=0)

df_with_missing.loc[:, 'age'] = rf_model.predict(x_missing)
# check the missing values
df_with_missing.isnull().sum().sort_values (ascending=False)

deck           158
pclass           0
survived         0
age              0
sibsp            0
parch            0
sex              0
fare             0
embarked         0
who              0
class            0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

In [100]:
# 
df = df.drop('deck', axis=1, errors='ignore')

In [101]:
df.isnull().sum().sort_values(ascending=False)

age            177
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64